#!/bin/bash
apt-get update
echo PACKAGE UPDATE COMPLETE!!! INSTALLING....
sleep 5
echo "...AND>>>>GO!!!! (NOTE: this is being dumped into syslog)"
apt-get install -y build-essential make logtail libtool automake autoconf pkg-config htop curl lynx-cur zlib1g* libpcre* libexpat* libconfuse* libapr1* >> /var/log/syslog
echo "adding ganglia user/group"
ln -s /usr/local/lib64/ganglia /usr/lib/ganglia
useradd --system ganglia
groupadd --system ganglia
echo UPDATE ALL DONE!!!
echo "Creating /etc/ganglia/"
mkdir /etc/ganglia
echo BEGINNING INSTALL!!!
## get repos
cd /tmp
git clone https://github.com/concurrencykit/ck.git
git clone https://github.com/ganglia/monitor-core.git
cd ck
./configure
make
make install
cd ../monitor-core
./bootstrap
./configure
make
make install
cd ~/
gmond -t >> /etc/ganglia/gmond.conf
echo "ALL DONE!!!"
vim /etc/ganglia/gmond.conf
