#!/bin/bash
apt-get update
apt-get install -y build-essential apache2 libapache2-mod-php5 rrdtool automake pkg-config htop curl lynx-cur zlib1g* libpcre* libexpat* libconfuse* libapr1* >> /var/log/syslog
a2enmod php5
service apache2 restart
