#!/bin/bash
apt-get update
apt-get install -y build-essential libtool automake pkg-config htop curl lynx-cur zlib1g* libpcre* libexpat* libconfuse* libapr1* >> /var/log/syslog
./DEPENDENCIES_SCRIPT
wget http://launchpadlibrarian.net/145655131/ganglia-webfrontend_3.5.8-3.1_all.deb
dpkg -i ganglia-webfrontend_3.5.8-3.1_all.deb
apt-get install -f
updatedb
cp /etc/ganglia-webfrontend/apache.conf /etc/apache2/sites-enabled/
service apache2 restart





