#!/bin/bash
apt-get update
echo PACKAGE UPDATE COMPLETE!!! INSTALLING....
sleep 5
echo "...AND>>>>GO!!!! (NOTE: this is being dumped into syslog)"
apt-get install -y build-essential make logtail automake autoconf pkg-config htop curl lynx-cur zlib1g* libpcre* libexpat* libconfuse* libapr1* >> /var/log/syslog
echo UPDATE ALL DONE!!!
echo BEGINNING INSTALL!!!
./configure
make
make install



